### ISSUE TITLE
Error: package or namespace load failed for ‘pairwiseComparisons’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):  there is no package called ‘rstan’

### ISSUE THREAD

**Issue by Xaviermelo** [IndrajeetPatil/pairwiseComparisons#18]
Hi,

I'm trying to instal the library pairwiseComparisons but I keep getting the same error. I'm running RStudio 1.3.1056 for R 4.02 on a macOS Catalina 10.15.6. Haven't had any problem with other libraries, so I wonder if you have a quickfix. 

> library(pairwiseComparisons)
Registered S3 method overwritten by 'broom.mixed':
  method      from 
  tidy.gamlss broom
Error: package or namespace load failed for ‘pairwiseComparisons’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rstan’

Tried to install lib.loc or .libPaths but I get the following mistake.
> install.packages("lib.loc")
Warning in install.packages :
  package ‘lib.loc’ is not available (for R version 4.0.2)

This (https://indrajeetpatil.github.io/pairwiseComparisons/) did not help either.

**Comment by IndrajeetPatil** [comment]
You just need to install `rstan` package. The installation fails because it can't find the needed `rstan` package.

If you have trouble installing `rstan`, please file an issue here: https://github.com/stan-dev/rstan/issues/

**Comment by Xaviermelo** [comment]
Thank you. I’ve tried that before but I’ll have a look on the posted
issues. It seems quite a few people are having similar issues.

Xavier
