### ISSUE TITLE
Package stuck solving

### ISSUE THREAD

**Issue by aw236** [IndrajeetPatil/pairwiseComparisons#29]
Having many issues trying to install. Tried with a fresh conda environment and it's been stuck on "solving" overnight.

![image](https://user-images.githubusercontent.com/8549939/120897562-d4ee2100-c5f4-11eb-9d64-86e05f94479d.png)

Do you have a list of packages to install, in a specific order, to get this following code to work?

```
# for reproducibility
set.seed(123)
library(ggstatsplot)

# plot
ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  title = "Distribution of sepal length across Iris species"
)
```

**Comment by IndrajeetPatil** [comment]
Hmm, unfortunately, I have no experience using the `conda` environment so not sure how this can be resolved. 😢 

I will install it and see if I can be of any help.

> Do you have a list of packages to install, in a specific order, to get this following code to work?

Ideally, just doing `install.packages("ggstatsplot")` should download all needed dependencies.

**Comment by IndrajeetPatil** [comment]
What do you see if you do the [following](https://anaconda.org/conda-forge/r-ggstatsplot)?

```
conda install -c conda-forge r-ggstatsplot
```

**Comment by IndrajeetPatil** [comment]
I can reproduce this behavior in _Anaconda_, but still not sure why this is happening or how to resolve it.

![image](https://user-images.githubusercontent.com/11330453/121313689-ed1cb380-c906-11eb-8c8b-450bb733216e.png)

**Comment by IndrajeetPatil** [comment]
Actually, I can't reproduce this. It took some time, but it did work:

![image](https://user-images.githubusercontent.com/11330453/121340015-62947e00-c91f-11eb-899e-dc5c63d4a7e6.png)

Maybe it was a temporary issue when it got stuck for you.
